### ISSUE TITLE
usePort signature should be changed

### ISSUE THREAD

**Issue by nyamsprod** [spatie/ssh#21]
Currently `usePort` method requires an `int` ?

https://github.com/spatie/ssh/blob/daace80f8abe943fb983a39ffe47855e91cd3ab6/src/Ssh.php#L40

What if I create a Ssh object with a specific port and I want to remove that port ? Currently this is not possible you should change the signature to `usePort(?int $port): self` IMHO.

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention. We'll take care of this soon by merge one of the currently opened PRs.
