### ISSUE TITLE
SSH Connection always ask for ssh key passphrase

### ISSUE THREAD

**Issue by mateusjunges** [spatie/ssh#30]
Good night,
I'm giving this package a try, and here is how i am connecting to my ssh host:

```php
\Spatie\Ssh\Ssh::create('MY USER', 'MY HOST')
            ->usePort(2222)
            ->usePrivateKey('path to my key file')
            ->execute('ls -la')
            ->getOutput()
```
Then, i run `php artisan serve`, and, in my linux terminal, this is the output:

```bash
started
[Fri Feb 14 00:08:36 2020] 127.0.0.1:44010 Accepted
[Fri Feb 14 00:08:36 2020] 127.0.0.1:44012 Accepted
Enter passphrase for key 'path_to_my_key_file': 
```
What i am doing wrong? Can't figure out what am i missing.

Thanks!

**Comment by rubenvanassche** [comment]
Hi @mateusjunges,

Seems like your private key is protected by a passphrase, could you try connecting to the host via ssh in the command line first? Normally you should provide a passphrase and then you're good to go. Maybe we should add support for providing passphrase, though I have no idea at the moment how we could do this.

**Comment by mateusjunges** [comment]
You are right, my Private key is protected by passphrase. Connecting to the host via terminal just work fine, and I need to type my passphrase only for the first connection. Then, I click the checkbox telling Linux to unlock my key file as soon as I log in to my PC. But, unfortunately, it doesn't work with `spatie/ssh`, and it ask for my passphrase for each connection.
Support for providing a passphrase would be awesome, but I don't know how to do it now. Will take some time to think about it.
Thanks!

**Comment by luchaos** [comment]
To not having to resort to storing the passphrase for the key on disk the system's ssh agent should be leveraged.
I raised a related issue a while ago which might be useful for that:
https://stackoverflow.com/questions/23161867/deployment-using-ssh-with-key-without-providing-passphrase-for-private-key-ssh
https://github.com/laravel/framework/issues/4235
https://github.com/laravel/framework/pull/4390

**Comment by beganovich** [comment]
I had same issue today. Is something like this acceptable and not dangerous? 

```php
\Spatie\Ssh\Ssh::create('MY USER', 'MY HOST')
            ->usePort(2222)
            ->usePrivateKey('path to my key file')
            ->password('my-secret') // note this
            ->execute('ls -la')
            ->getOutput()
```
