### ISSUE TITLE
'ssh' is not recognized as an internal or external command, [ Windows ]

### ISSUE THREAD

**Issue by MehdiAroui** [spatie/ssh#34]
Hi everyone,

I'm used the package, but I got that error even the ssh is installed and configured ( added to PATH and I can run ssh commens anywhere ) 

Did someOne have an idea wha would be the problem, thanks.

**Comment by aanderse** [comment]
@spatie would you be willing to make the path to the `ssh` executable configurable? In some deployments `ssh` may not be in `PATH`.

**Comment by freekmurze** [comment]
@aanderse feel free to submit a PR for that 👍
