### ISSUE TITLE
Access to remote server

### ISSUE THREAD

**Issue by lovecoding-git** [spatie/ssh#36]
Hi @freekmurze 

Thank you for your great package.
Can I ask one thing?
This package provides for only hosted project?

```Ssh::create('user', 'host')->usePrivateKey('/home/user/.ssh/id_rsa');```

It seems I need to use this command to access to remote server, right?

Then if someone knows my `user` and `privateKey path` then can anyone access to server?
I was a bit confused.

Is there any way to access SSH using username & password or something like that?

Thank you!

**Comment by freekmurze** [comment]
Currently that is not supported because I didn't need it. If this is simple to add, I'd accept a PR with tests and update docs that adds this to the package.
