### ISSUE TITLE
General error - windows

### ISSUE THREAD

**Issue by FluffyDiscord** [spatie/ssh#41]
Hi, is this package compatible with Windows ?

Every time I want to execute any kind of command, I get `General Error` in error text output and theres no real output, like should be.

```php
$ssh = \Spatie\Ssh\Ssh::create($user, $host, $port);
echo $ssh->execute('ls -l')->getExitCodeText(); // result is "General error"
```

Maybe it does not like the command syntax ?

```
ssh -p 12345 user@example.com 'bash -se' << \EOF-SPATIE-SSH
ls -l
EOF-SPATIE-SSH
```

**Comment by freekmurze** [comment]
I did not test it on windows, as I'm not needing that myself. 

Feel free to submit a PR that fixes this for you.

**Comment by schrink** [comment]
@freekmurze I really love what you do and appreciate all the open-source work you did. I was using your libraries hundreds of times. I have huge respect for you. 

But this kind of answer "I don't give a f***k" and then closing the issue is really rude and disappointing :(

**Comment by ben221199** [comment]
@FluffyDiscord This is because the `<<` is used and Windows cannot handle that operator properly in this case. I made a pull request to fix it: https://github.com/spatie/ssh/pull/64.
