### ISSUE TITLE
Missing environment variables

### ISSUE THREAD

**Issue by jonathanlundstrom** [spatie/ssh#56]
Hi,

I'm using this library (among others) to create a CLI application wrapping a local Laravel Homestead environment, so that developers can interact with artisan and other build tools without having to SSH into the machine themselves. Unfortunately, I've noticed that if I issue an `export` command with this library, none of the needed environment variables are not there.

If I on the other hand just issue `ssh vagrant@localhost -p 2222` on my local system – it all works as expected.

Why could this be, and how can I get around it?

The setup is running two sites and the database environment is specified through `Homestead.yaml` but it's all there if I do a regular SSH. Only through this library are the variables missing.'

Thanks,
Jonathan

**Comment by jonathanlundstrom** [comment]
Alright, so the issue is that this package spawns a new shell, and doesn't just roll with the default, which in our case is `zsh`, but the problem would be the same even if we were using `bash`. Simply removing the `bash -se` argument on this line resolves it, and doesn't seem to cause any additional side effects.

https://github.com/spatie/ssh/blob/main/src/Ssh.php#L145

Is there any valid reason why it's there in the first place?

**Comment by freekmurze** [comment]
Removing these options would mean a breaking change. You can look up the meaning of options in the bash docs. I'd accept a PR that allows to override these options. Make sure to add tests + update the readme.

**Comment by jonathanlundstrom** [comment]
Could you explain in which way it would mean a breaking change? It seems obvious that you know more than I on this, but through reading I have not been able to ascertain a reason for keeping it.

I'll look into making a PR for this, but I want to understand before I do. Also, is there any other way that you know of to keep the exported variables?

**Comment by freekmurze** [comment]
> Could you explain in which way it would mean a breaking change?

Some people might rely on the current behaviour of the given options.
