### ISSUE TITLE
Bug: Using public setTimeout creates invalid SSH commands

### ISSUE THREAD

**Issue by iPwnPancakes** [spatie/ssh#86]
Hello!

I noticed when using this package in production that using the setTimeout function actually causes the resulting SSH command to be invalid. If you add this test:
```php
it('setting timeout does not alter ssh command', function () {
    $command = $this->ssh->setTimeout(10)->getExecuteCommand('whoami');

    assertMatchesSnapshot($command);
});
```

You will see this result:
```bash
ssh 10 user@example.com 'bash -se' << \EOF-SPATIE-SSH
whoami
EOF-SPATIE-SSH
```

When checking the [ssh man page](https://linux.die.net/man/1/ssh), it seems that the correct usage is to pass it in as an option as `-o ConnectTimeout=10`. But instead it is serialized as an integer due to the way `getExecuteCommand` turns everything in the `$this->extraOptions` array to a string.

Though I do see that this option is intended to merely pass the integer to Symfony's `Process` class.

**Comment by freekmurze** [comment]
Thanks for the PR 👍
