### ISSUE TITLE
SSH connection without specifying a user

### ISSUE THREAD

**Issue by pyrech** [spatie/ssh#97]
We often define the SSH access configuration in the SSH config file (f.e. in `~/.ssh/config`):

```
Host my-prod
    Hostname x.x.x.x
    User debian
```

In such cases, we can connect to the server with only `ssh my-prod`. But unless I'm wrong, this is not possible at the moment as the `user` argument is always mandatory in spatie/ssh.

Would it be possible to make it optional? I could give it a try if you would accept such a PR :slightly_smiling_face:

**Comment by freekmurze** [comment]
Feel free to send a PR for this.
